# Reference: https://kubernetes.io/docs/concepts/configuration/configmap/
# Title: configmap-web1 - one website for deployment 1
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-web1
data:
  # custom index.html file-like keys
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Deployment One</title>
      </head>
      <body>
        <p>This is Deployment One hosting clothing and accessories websites.</p>
      </body>
    </html>
---
# configmap-web2 - another website for deployment 2
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-web2
data:
  # custom index.html file-like keys
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Deployment Two</title>
      </head>
      <body>
        <p>This is Deployment Two hosting as a home decor website.</p>
      </body>
    </html>