version: '3.8'

services:
  frontend:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  
  backend:
    image: python
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

